# Project: game-chicken-run
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o screenslib.o
LINKOBJ  = main.o screenslib.o
LIBS     = -L"C:/Development/Dev-Cpp/MinGW64/lib32" -L"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"C:/Development/Dev-Cpp/lib" -lconio -m32 -g3
INCS     = -I"C:/Development/Dev-Cpp/MinGW64/include" -I"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Development/Dev-Cpp/include"
CXXINCS  = -I"C:/Development/Dev-Cpp/MinGW64/include" -I"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Development/Dev-Cpp/include"
BIN      = game-chicken-run.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

screenslib.o: screenslib.c
	$(CC) -c screenslib.c -o screenslib.o $(CFLAGS)
